### ISSUE TITLE
Material already registered error

### ISSUE THREAD

**Issue by yggdrasil75** [WhiskyTangoFawks/WTFTools#1]
When attempting to load the mod I found an error where silver pick head was registered twice. This may be due to one of the lower quality mods I have installed which probably does not use the ore dict properly but otherwise I will leave it up to you.

[Gist](https://gist.github.com/yggdrasil75/4d5b0ddc5d00bb18c5f40fbc72ecfe18)

**Comment by WhiskyTangoFawks** [comment]
I think, it's the result of two mods adding silver as a material, so it's in the list twice, and my mod tries to make two sets of tool heads for it- which it doesn't need to do.  Does silver by any chance show up in the config twice?

**Comment by yggdrasil75** [comment]
When it crashed it did not fill the config. I do know that there are several mods that add silver tools in my pack though. Probably three different tool sets.

**Comment by WhiskyTangoFawks** [comment]
Alright, that should in theory be a simple enough thing to fix.

**Comment by WhiskyTangoFawks** [comment]
Fix just went up to curseforge.
